// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hashicorp/nomad-autoscaler/pkg/node (interfaces: Status)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/pkg/node/node.go . Status
//

// Package mock_node is a generated GoMock package.
package mock_node

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStatus is a mock of Status interface.
type MockStatus struct {
	ctrl     *gomock.Controller
	recorder *MockStatusMockRecorder
	isgomock struct{}
}

// MockStatusMockRecorder is the mock recorder for MockStatus.
type MockStatusMockRecorder struct {
	mock *MockStatus
}

// NewMockStatus creates a new mock instance.
func NewMockStatus(ctrl *gomock.Controller) *MockStatus {
	mock := &MockStatus{ctrl: ctrl}
	mock.recorder = &MockStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatus) EXPECT() *MockStatusMockRecorder {
	return m.recorder
}

// IsIneligible mocks base method.
func (m *MockStatus) IsIneligible(nodeID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsIneligible", nodeID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsIneligible indicates an expected call of IsIneligible.
func (mr *MockStatusMockRecorder) IsIneligible(nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsIneligible", reflect.TypeOf((*MockStatus)(nil).IsIneligible), nodeID)
}

// IsUnavailable mocks base method.
func (m *MockStatus) IsUnavailable(nodeID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUnavailable", nodeID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUnavailable indicates an expected call of IsUnavailable.
func (mr *MockStatusMockRecorder) IsUnavailable(nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUnavailable", reflect.TypeOf((*MockStatus)(nil).IsUnavailable), nodeID)
}

// Stats mocks base method.
func (m *MockStatus) Stats() (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockStatusMockRecorder) Stats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockStatus)(nil).Stats))
}
